export const SELECTED_SETTINGS = 'SELECTED_SETTINGS';
export const ALL_SITES_DATA = 'ALL_SITES_DATA';
export const SINGLE_SITE_DATA = 'SINGLE_SITE_DATA';
export const SELECTED_PROJECTS = 'SELECTED_PROJECTS';
export const SITES_AND_PROJECT = 'SITES_AND_PROJECT';
export const DAMAGE_SUMMARY_LEFT = 'DAMAGE_SUMMARY_LEFT'